name: docs CI

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - '!*'
      - '!.vscode/**'
      - '!src/**'
      - '!playground/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm
      - name: Install dependencies
        run: pnpm install
      - name: Build
        run: pnpm docs:build
      - name: Checkout target repo
        uses: actions/checkout@v4
        with:
          repository: vc-dock/vc-dock.github.io
          token: ${{ secrets.DEPLOY_TOKEN }}
          path: dest
      - name: Clear target repo
        run: |
          rm -rf ./dest/*
          cp -R /home/runner/work/vc-dock/vc-dock/docs/.vitepress/dist/* ./dest/
      - name: Commit and push changes to target repo
        run: |
          cd dest
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add .
          git commit -a -m "Update build artifact"
          git push -f
